CREATE TABLE DEPARTMENT (
    DNUM INT PRIMARY KEY,
    DName VARCHAR(100) NOT NULL,
    Location VARCHAR(100)
);

CREATE TABLE EMPLOYEE (
    SSN CHAR(9) PRIMARY KEY,
    Fname VARCHAR(50) NOT NULL,
    Lname VARCHAR(50) NOT NULL,
    gender CHAR(1) CHECK (gender IN ('M', 'F')),
    super_id CHAR(9),
    BirthDate DATE,
    DNUM INT,
    HireDate DATE,
    FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM),
    FOREIGN KEY (super_id) REFERENCES EMPLOYEE(SSN)
);

CREATE TABLE PROJECT (
    PNumber INT PRIMARY KEY,
    PName VARCHAR(100) NOT NULL,
    Location VARCHAR(100),
    CITY VARCHAR(50),
    DNUM INT,
    FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM)
);

CREATE TABLE WORK (
    SSN CHAR(9),
    PNumber INT,
    hours DECIMAL(5,2) CHECK (hours >= 0),
    PRIMARY KEY (SSN, PNumber),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN),
    FOREIGN KEY (PNumber) REFERENCES PROJECT(PNumber)
);

CREATE TABLE DEPENDENT (
    DependentName VARCHAR(50) NOT NULL,
    BirthDate DATE,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    SSN CHAR(9),
    PRIMARY KEY (DependentName, SSN),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN)
);

CREATE TABLE LOCATION (
    DNUM INT,
    Location VARCHAR(100),
    PRIMARY KEY (DNUM, Location),
    FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM)
);
